dotenv: .env
wallets:
  pkey_lb_official: ${PKEY_LB_OFFICIAL}
  pkey_lb_test: ${PKEY_LB_TEST}
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts'